In [2]:
import pandas as pd

In [3]:
df_costs = pd.read_csv('costs.csv')
df_courier_staff = pd.read_csv('courier_staff.csv')
df_routes = pd.read_csv('routes.csv')
df_shipment_tracking = pd.read_csv('shipment_tracking.csv')
df_shipments = pd.read_json('shipments.json')
df_warehouses = pd.read_json('warehouses.json')

In [4]:
print(df_shipments.shape)
df_shipments.head()

(70000, 8)

,shipment_id,order_date,origin,destination,weight,courier_id,status,delivery_date
0,dc84cc15,2025-06-12,North Dawnfort,Ginafort,43.52,b554e6a4,Cancelled,None
1,ca536e73,2025-06-27,North Williamchester,Christinechester,19.31,9b44d9ca,Cancelled,None
2,704fa19e,2025-09-09,New Colleen,West Jared,27.97,f8c3e908,Delivered,2025-09-13
3,aad8a598,2025-07-25,South Ashleystad,Jonestown,18.74,0de3fc1b,Cancelled,None
4,e120d4ba,2026-01-06,Darinton,West Jared,39.30,44def2f4,In Transit,None

In [4]:
print(df_costs.shape)
df_costs.head()

(70000, 4)

  shipment_id  fuel_cost  labor_cost  misc_cost
0    dc84cc15      61.08       27.24      20.75
1    ca536e73      13.74       65.13      17.63
2    704fa19e      72.68       39.47      16.84
3    aad8a598      53.69       23.23      33.16
4    e120d4ba      90.24      107.29      14.73

In [5]:
print(df_shipment_tracking.shape)
df_shipment_tracking.head()

(209570, 4)

   tracking_id shipment_id        status            timestamp
0            1    dc84cc15  Order Placed  2025-06-12 02:00:00
1            2    dc84cc15     Cancelled  2025-06-15 00:00:00
2            3    ca536e73  Order Placed  2025-06-27 02:00:00
3            4    ca536e73     Cancelled  2025-06-28 00:00:00
4            5    704fa19e  Order Placed  2025-09-09 03:00:00

In [6]:
print(df_courier_staff.shape)
df_courier_staff.head()

(1000, 4)

  courier_id           name  rating vehicle_type
0   7bc57152   Justin Flynn     4.8          Van
1   87cafee3  Sherry Conrad     3.2        Truck
2   53cc593b     Joanna Liu     4.0          Car
3   c482832b   Samantha Lee     4.9          Car
4   a217d894  Carrie Santos     3.9          Van

In [7]:
print(df_routes.shape)
df_routes.head()

(500, 5)

   route_id         origin     destination  distance_km  avg_time_hours
0  fe423f38  East Victoria   South Raymond      1016.50            44.2
1  080ff620     Mooreshire      Davidshire        58.30            45.3
2  aa6e4a5f     Mooreshire   South Raymond       977.98            42.4
3  3aa7af93        Kimfort  East Johnshire       691.84            35.7
4  39913248     Tiffanyton      East David      1836.43            24.4

In [8]:
print(df_warehouses.shape)
df_warehouses.head()

(50, 4)

  warehouse_id                  city state  capacity
0     647a65d8     North Claudiatown    SC      9821
1     8bdbd012            East David    MT      1138
2     cfcbd086          North Justin    ND      6019
3     3bff4497    Port Sandrachester    CT      3300
4     6767e7a4  North Williamchester    SD      6822

In [9]:
df_shipments.isnull().sum()

shipment_id          0
order_date           0
origin               0
destination          0
weight               0
courier_id           0
status               0
delivery_date    52664
dtype: int64

In [10]:
df_costs.isnull().sum()

shipment_id    0
fuel_cost      0
labor_cost     0
misc_cost      0
dtype: int64

In [11]:
df_shipment_tracking.isnull().sum()

tracking_id    0
shipment_id    0
status         0
timestamp      0
dtype: int64

In [12]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\hunte\anaconda3\lib\site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import mysql.connector

In [14]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="JaiKomal@Puja04",
    database="logistics_db"
)
cursor = conn.cursor()

In [15]:
cursor.execute("SHOW TABLES;")
tables = cursor.fetchall()
print("Tables in database:")
for t in tables:
    print(t[0])

Tables in database:
costs
courier_staff
routes
shipment_tracking
shipments
warehouses

In [16]:
for table in ["shipments", "shipment_tracking", "courier_staff", "routes", "warehouses", "costs"]:
    print(f"\nColumns in {table}:")
    cursor.execute(f"DESCRIBE {table};")
    for col in cursor.fetchall():
        print(col[0])

Columns in shipments:
shipment_id
order_date
origin
destination
weight
courier_id
status
delivery_date

Columns in shipment_tracking:
tracking_id
shipment_id
status
timestamp

Columns in courier_staff:
courier_id
name
rating
vehicle_type

Columns in routes:
route_id
origin
destination
distance_km
avg_time_hours

Columns in warehouses:
warehouse_id
city
state
capacity

Columns in costs:
shipment_id
fuel_cost
labor_cost
misc_cost

In [17]:
# Insert warehouses
for index, row in df_warehouses.iterrows():
    cursor.execute("INSERT IGNORE INTO warehouses (warehouse_id, city, state, capacity) VALUES (%s, %s, %s, %s)",
    (row['warehouse_id'], row['city'], row['state'], row['capacity']))
conn.commit()
print("Warehouses done!")

# Insert courier_staff
for index, row in df_courier_staff.iterrows():
    cursor.execute("INSERT IGNORE INTO courier_staff (courier_id, name, rating, vehicle_type) VALUES (%s, %s, %s, %s)",
    (row['courier_id'], row['name'], row['rating'], row['vehicle_type']))
conn.commit()
print("Courier staff done!")

# Insert routes
for index, row in df_routes.iterrows():
    cursor.execute("INSERT IGNORE INTO routes (route_id, origin, destination, distance_km, avg_time_hours) VALUES (%s, %s, %s, %s, %s)",
    (row['route_id'], row['origin'], row['destination'], row['distance_km'], row['avg_time_hours']))
conn.commit()
print("Routes done!")

# Insert shipments
for index, row in df_shipments.iterrows():
    cursor.execute("INSERT IGNORE INTO shipments (shipment_id, order_date, origin, destination, weight, courier_id, status, delivery_date) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
    (row['shipment_id'], row['order_date'], row['origin'], row['destination'], row['weight'], row['courier_id'], row['status'], row['delivery_date']))
conn.commit()
print("Shipments done!")

# Insert shipment_tracking
for index, row in df_shipment_tracking.iterrows():
    cursor.execute("INSERT IGNORE INTO shipment_tracking (tracking_id, shipment_id, status, timestamp) VALUES (%s, %s, %s, %s)",
    (row['tracking_id'], row['shipment_id'], row['status'], row['timestamp']))
conn.commit()
print("Tracking done!")

# Insert costs
for index, row in df_costs.iterrows():
    cursor.execute("INSERT IGNORE INTO costs (shipment_id, fuel_cost, labor_cost, misc_cost) VALUES (%s, %s, %s, %s)",
    (row['shipment_id'], row['fuel_cost'], row['labor_cost'], row['misc_cost']))
conn.commit()
print("Costs done!")

print("All data loaded into MySQL!")

Warehouses done!
Courier staff done!
Routes done!
Shipments done!
Tracking done!
Costs done!
All data loaded into MySQL!

if page == '🔍 Shipment Search':
    st.title('🔍 Shipment Search & Filtering')
    search_id = st.text_input('Search by Shipment ID')
    origin_filter = st.text_input('Filter by Origin')
    from_date = st.date_input(' From Date')
    to_date = st.date_input('To Date')
    courier_filter = st.text_input('Search by Courier ID')
    status_filter = st.selectbox('Filter by Status',['All', 'Delivered', 'Cancelled', 'In Transit'])
    if search_id:
        df = fetch_data('SELECT * FROM shipments WHERE shipment_id LIKE %s',[f'%{search_id}%'])
    elif status_filter != 'All':
        df =  fetch_data('SELECT * FROM shipments WHERE status = %s',[status_filter])
    else:
        df = fetch_data('SELECT * FROM shipments LIMIT 100')
    st.subheader('Shipment Results')
    st.dataframe(df)




    cd "C:\Users\hunte\VS Code\Logistic_Project"
streamlit run logistic_app.py